<?php

/**
 * BaseConnection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $node_id
 * @property string $token
 * @property string $status
 * @property string $mac
 * @property string $ip
 * @property string $auth_type
 * @property string $identity
 * @property float $incoming
 * @property float $outgoing
 * @property Node $Node
 * 
 * @method integer    getNodeId()    Returns the current record's "node_id" value
 * @method string     getToken()     Returns the current record's "token" value
 * @method string     getStatus()    Returns the current record's "status" value
 * @method string     getMac()       Returns the current record's "mac" value
 * @method string     getIp()        Returns the current record's "ip" value
 * @method string     getAuthType()  Returns the current record's "auth_type" value
 * @method string     getIdentity()  Returns the current record's "identity" value
 * @method float      getIncoming()  Returns the current record's "incoming" value
 * @method float      getOutgoing()  Returns the current record's "outgoing" value
 * @method Node       getNode()      Returns the current record's "Node" value
 * @method Connection setNodeId()    Sets the current record's "node_id" value
 * @method Connection setToken()     Sets the current record's "token" value
 * @method Connection setStatus()    Sets the current record's "status" value
 * @method Connection setMac()       Sets the current record's "mac" value
 * @method Connection setIp()        Sets the current record's "ip" value
 * @method Connection setAuthType()  Sets the current record's "auth_type" value
 * @method Connection setIdentity()  Sets the current record's "identity" value
 * @method Connection setIncoming()  Sets the current record's "incoming" value
 * @method Connection setOutgoing()  Sets the current record's "outgoing" value
 * @method Connection setNode()      Sets the current record's "Node" value
 * 
 * @package    authpuppy
 * @subpackage model
 * @author     Frédéric Sheedy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConnection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('connections');
        $this->hasColumn('node_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('mac', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('auth_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('identity', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('incoming', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('outgoing', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             'model' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Node', array(
             'local' => 'node_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}