<?php

/**
 * BaseapPluginConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $pluginname
 * @property string $config_option
 * @property string $config_value
 * 
 * @method string         getPluginname()    Returns the current record's "pluginname" value
 * @method string         getConfigOption()  Returns the current record's "config_option" value
 * @method string         getConfigValue()   Returns the current record's "config_value" value
 * @method apPluginConfig setPluginname()    Sets the current record's "pluginname" value
 * @method apPluginConfig setConfigOption()  Sets the current record's "config_option" value
 * @method apPluginConfig setConfigValue()   Sets the current record's "config_value" value
 * 
 * @package    authpuppy
 * @subpackage model
 * @author     Frédéric Sheedy
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseapPluginConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_plugin_config');
        $this->hasColumn('pluginname', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('config_option', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('config_value', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}